spark.sql.catalogImplementation            hive
spark.hadoop.hive.metastore.uris           thrift://hive-metastore:9083
spark.sql.hive.metastore.version           4.0.1
spark.sql.hive.metastore.jars              maven
spark.sql.warehouse.dir                    hdfs://hdfs:9000/user/hive/warehouse
spark.hadoop.fs.defaultFS                  hdfs://hdfs:9000
spark.sql.orc.impl                         native
spark.sql.hive.convertMetastoreOrc         true
